//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intsis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpertSystemV2Entities : DbContext
    {
        public ExpertSystemV2Entities()
            : base("name=ExpertSystemV2Entities")
        {
        }
        private static ExpertSystemV2Entities context;
        public static ExpertSystemV2Entities GetContext()
        {
            if (context == null)
            {
                context = new ExpertSystemV2Entities();
            }
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<ExpSystems> ExpSystems { get; set; }
        public virtual DbSet<Facts> Facts { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<TypeOfSys> TypeOfSys { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeightAnswers> WeightAnswers { get; set; }
    }
}
