
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace intsis
{

using System;
    using System.Collections.Generic;
    
public partial class LinearSystem_Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LinearSystem_Question()
    {

        this.LinearSystem_Answer = new HashSet<LinearSystem_Answer>();

    }


    public int Id { get; set; }

    public Nullable<int> SystemId { get; set; }

    public string Text { get; set; }



    public virtual ExpSystem ExpSystem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LinearSystem_Answer> LinearSystem_Answer { get; set; }

}

}
