
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace intsis
{

using System;
    using System.Collections.Generic;
    
public partial class LinearSystem_Answer
{

    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string Text { get; set; }

    public Nullable<int> NextQuestionId { get; set; }

    public string Recomendation { get; set; }

    public string Out { get; set; }



    public virtual LinearSystem_Question LinearSystem_Question { get; set; }

}

}
