//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intsis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ExpertSystemEntities : DbContext
    {
        public ExpertSystemEntities()
            : base("name=ExpertSystemEntities")
        {
            Database.SetInitializer(new CreateDatabaseIfNotExists<ExpertSystemEntities>());
            Database.Log = log => System.Diagnostics.Debug.WriteLine(log);
        }
        private static ExpertSystemEntities context;
        public static ExpertSystemEntities GetContext()
        {
            if (context == null)
                context = new ExpertSystemEntities();
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ExpSystem> ExpSystem { get; set; }
        public virtual DbSet<LinearSystem_Answer> LinearSystem_Answer { get; set; }
        public virtual DbSet<LinearSystem_Question> LinearSystem_Question { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WeightedSystem_Answer> WeightedSystem_Answer { get; set; }
        public virtual DbSet<WeightedSystem_Fact> WeightedSystem_Fact { get; set; }
        public virtual DbSet<WeightedSystem_Question> WeightedSystem_Question { get; set; }
        public virtual DbSet<WeightFactAnswer> WeightFactAnswer { get; set; }
    }
}
