//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intsis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class intsisEntities : DbContext
    {
        public intsisEntities()
            : base("name=intsisEntities")
        {
        }
        private static intsisEntities context_;
        public static intsisEntities GetContext()
        {
            if (context_ == null)
                context_ = new intsisEntities();
            return context_;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NameSis> NameSis { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Rules> Rules { get; set; }
    }
}
