
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace intsis
{

using System;
    using System.Collections.Generic;
    
public partial class WeightedSystem_Answer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WeightedSystem_Answer()
    {

        this.WeightFactAnswer = new HashSet<WeightFactAnswer>();

    }


    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string Text { get; set; }

    public string Recomendation { get; set; }



    public virtual WeightedSystem_Question WeightedSystem_Question { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WeightFactAnswer> WeightFactAnswer { get; set; }

}

}
