
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace intsis
{

using System;
    using System.Collections.Generic;
    
public partial class WeightedSystem_Fact
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WeightedSystem_Fact()
    {

        this.WeightedSystem_Question = new HashSet<WeightedSystem_Question>();

    }


    public int Id { get; set; }

    public int SystemId { get; set; }

    public string Name { get; set; }

    public string Text { get; set; }



    public virtual ExpSystem ExpSystem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WeightedSystem_Question> WeightedSystem_Question { get; set; }

}

}
