//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intsis
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightAnswers
    {
        public int WAID { get; set; }
        public int FactID { get; set; }
        public int AnswerID { get; set; }
        public bool PlusOrMinus { get; set; }
        public decimal Value { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Facts Facts { get; set; }
    }
}
