//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intsis
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightedSystem_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeightedSystem_Question()
        {
            this.WeightedSystem_Answer = new HashSet<WeightedSystem_Answer>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int FactID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightedSystem_Answer> WeightedSystem_Answer { get; set; }
        public virtual WeightedSystem_Fact WeightedSystem_Fact { get; set; }
    }
}
